CREATE NAMESPACE IF NOT EXISTS demo.ctl;
CREATE NAMESPACE IF NOT EXISTS demo.bronze;
CREATE NAMESPACE IF NOT EXISTS demo.silver;
CREATE NAMESPACE IF NOT EXISTS demo.gold;

CREATE TABLE IF NOT EXISTS demo.ctl.source_registration (
    source_name STRING,
    domain_name STRING,
    source_type STRING,
    source_object STRING,
    enabled BOOLEAN,
    load_mode STRING,
    base_extract_sql STRING,
    watermark_column STRING,
    watermark_type STRING,
    primary_keys ARRAY<STRING>,
    sequence_column STRING,
    delete_indicator_column STRING,
    bronze_table STRING,
    silver_current_table STRING,
    silver_history_table STRING,
    gold_table STRING,
    silver_transform_name STRING,
    gold_publish_name STRING,
    quality_rule_set STRING,
    replay_mode_default STRING,
    options_json STRING,
    last_successful_watermark STRING,
    last_batch_id BIGINT,
    created_ts TIMESTAMP,
    updated_ts TIMESTAMP
) USING iceberg;

CREATE TABLE IF NOT EXISTS demo.ctl.pipeline_run (
    batch_id BIGINT,
    source_name STRING,
    run_mode STRING,
    run_status STRING,
    requested_by STRING,
    replay_request_id BIGINT,
    run_start_ts TIMESTAMP,
    run_end_ts TIMESTAMP,
    rows_read BIGINT,
    bronze_rows_written BIGINT,
    silver_rows_written BIGINT,
    gold_rows_written BIGINT,
    quality_status STRING,
    watermark_value STRING,
    error_message STRING
) USING iceberg;

CREATE TABLE IF NOT EXISTS demo.ctl.quality_result (
    batch_id BIGINT,
    source_name STRING,
    rule_name STRING,
    rule_status STRING,
    observed_value STRING,
    expected_value STRING,
    details STRING,
    evaluated_ts TIMESTAMP
) USING iceberg;

CREATE TABLE IF NOT EXISTS demo.ctl.replay_request (
    replay_request_id BIGINT,
    source_name STRING,
    replay_mode STRING,
    start_watermark STRING,
    end_watermark STRING,
    entity_predicate STRING,
    snapshot_id BIGINT,
    target_table STRING,
    requested_by STRING,
    request_status STRING,
    requested_ts TIMESTAMP,
    started_ts TIMESTAMP,
    completed_ts TIMESTAMP,
    notes STRING
) USING iceberg;

MERGE INTO demo.ctl.source_registration AS target
USING (
    SELECT
        'customer' AS source_name,
        'sales' AS domain_name,
        'TABLE' AS source_type,
        'demo.staging.customer_source' AS source_object,
        true AS enabled,
        'INCREMENTAL_TS' AS load_mode,
        CAST(NULL AS STRING) AS base_extract_sql,
        'source_change_ts' AS watermark_column,
        'TIMESTAMP' AS watermark_type,
        ARRAY('customer_id') AS primary_keys,
        CAST(NULL AS STRING) AS sequence_column,
        CAST(NULL AS STRING) AS delete_indicator_column,
        'demo.bronze.customer_incremental_iceberg' AS bronze_table,
        'demo.silver.customer_current_iceberg' AS silver_current_table,
        'demo.silver.customer_history_iceberg' AS silver_history_table,
        'demo.gold.customer_serving_iceberg' AS gold_table,
        'scd2_current_history' AS silver_transform_name,
        'publish_current_snapshot' AS gold_publish_name,
        'customer_core' AS quality_rule_set,
        'FULL_REBUILD' AS replay_mode_default,
        '{"required_columns":["customer_id","location","source_change_ts"]}' AS options_json,
        CAST(NULL AS STRING) AS last_successful_watermark,
        CAST(NULL AS BIGINT) AS last_batch_id,
        current_timestamp() AS created_ts,
        current_timestamp() AS updated_ts
    UNION ALL
    SELECT
        'orders' AS source_name,
        'sales' AS domain_name,
        'TABLE' AS source_type,
        'demo.staging.orders_source' AS source_object,
        true AS enabled,
        'INCREMENTAL_TS' AS load_mode,
        CAST(NULL AS STRING) AS base_extract_sql,
        'source_change_ts' AS watermark_column,
        'TIMESTAMP' AS watermark_type,
        ARRAY('order_id') AS primary_keys,
        CAST(NULL AS STRING) AS sequence_column,
        CAST(NULL AS STRING) AS delete_indicator_column,
        'demo.bronze.orders_incremental_iceberg' AS bronze_table,
        'demo.silver.orders_current_iceberg' AS silver_current_table,
        'demo.silver.orders_history_iceberg' AS silver_history_table,
        'demo.gold.orders_serving_iceberg' AS gold_table,
        'scd2_current_history' AS silver_transform_name,
        'publish_current_snapshot' AS gold_publish_name,
        'orders_core' AS quality_rule_set,
        'FULL_REBUILD' AS replay_mode_default,
        '{"required_columns":["order_id","customer_id","order_status","source_change_ts"]}' AS options_json,
        CAST(NULL AS STRING) AS last_successful_watermark,
        CAST(NULL AS BIGINT) AS last_batch_id,
        current_timestamp() AS created_ts,
        current_timestamp() AS updated_ts
    UNION ALL
    SELECT
        'product' AS source_name,
        'sales' AS domain_name,
        'TABLE' AS source_type,
        'demo.staging.product_source' AS source_object,
        true AS enabled,
        'FULL' AS load_mode,
        CAST(NULL AS STRING) AS base_extract_sql,
        'source_change_ts' AS watermark_column,
        'TIMESTAMP' AS watermark_type,
        ARRAY('product_id') AS primary_keys,
        CAST(NULL AS STRING) AS sequence_column,
        CAST(NULL AS STRING) AS delete_indicator_column,
        'demo.bronze.product_snapshot_iceberg' AS bronze_table,
        'demo.silver.product_current_iceberg' AS silver_current_table,
        'demo.silver.product_history_iceberg' AS silver_history_table,
        'demo.gold.product_serving_iceberg' AS gold_table,
        'scd2_current_history' AS silver_transform_name,
        'publish_current_snapshot' AS gold_publish_name,
        'product_core' AS quality_rule_set,
        'FULL_REBUILD' AS replay_mode_default,
        '{"required_columns":["product_id","product_name","category","source_change_ts"]}' AS options_json,
        CAST(NULL AS STRING) AS last_successful_watermark,
        CAST(NULL AS BIGINT) AS last_batch_id,
        current_timestamp() AS created_ts,
        current_timestamp() AS updated_ts
    UNION ALL
    SELECT
        'invoice' AS source_name,
        'sales' AS domain_name,
        'TABLE' AS source_type,
        'demo.staging.invoice_source' AS source_object,
        true AS enabled,
        'INCREMENTAL_TS' AS load_mode,
        CAST(NULL AS STRING) AS base_extract_sql,
        'source_change_ts' AS watermark_column,
        'TIMESTAMP' AS watermark_type,
        ARRAY('invoice_id') AS primary_keys,
        CAST(NULL AS STRING) AS sequence_column,
        CAST(NULL AS STRING) AS delete_indicator_column,
        'demo.bronze.invoice_incremental_iceberg' AS bronze_table,
        'demo.silver.invoice_current_iceberg' AS silver_current_table,
        'demo.silver.invoice_history_iceberg' AS silver_history_table,
        'demo.gold.invoice_serving_iceberg' AS gold_table,
        'scd2_current_history' AS silver_transform_name,
        'publish_current_snapshot' AS gold_publish_name,
        'invoice_core' AS quality_rule_set,
        'FULL_REBUILD' AS replay_mode_default,
        '{"required_columns":["invoice_id","order_id","invoice_status","source_change_ts"]}' AS options_json,
        CAST(NULL AS STRING) AS last_successful_watermark,
        CAST(NULL AS BIGINT) AS last_batch_id,
        current_timestamp() AS created_ts,
        current_timestamp() AS updated_ts
    UNION ALL
    SELECT
        'shipment' AS source_name,
        'sales' AS domain_name,
        'TABLE' AS source_type,
        'demo.staging.shipment_source' AS source_object,
        true AS enabled,
        'INCREMENTAL_TS' AS load_mode,
        CAST(NULL AS STRING) AS base_extract_sql,
        'source_change_ts' AS watermark_column,
        'TIMESTAMP' AS watermark_type,
        ARRAY('shipment_id') AS primary_keys,
        CAST(NULL AS STRING) AS sequence_column,
        CAST(NULL AS STRING) AS delete_indicator_column,
        'demo.bronze.shipment_incremental_iceberg' AS bronze_table,
        'demo.silver.shipment_current_iceberg' AS silver_current_table,
        'demo.silver.shipment_history_iceberg' AS silver_history_table,
        'demo.gold.shipment_serving_iceberg' AS gold_table,
        'scd2_current_history' AS silver_transform_name,
        'publish_current_snapshot' AS gold_publish_name,
        'shipment_core' AS quality_rule_set,
        'FULL_REBUILD' AS replay_mode_default,
        '{"required_columns":["shipment_id","order_id","shipment_status","source_change_ts"]}' AS options_json,
        CAST(NULL AS STRING) AS last_successful_watermark,
        CAST(NULL AS BIGINT) AS last_batch_id,
        current_timestamp() AS created_ts,
        current_timestamp() AS updated_ts
) AS source
ON target.source_name = source.source_name
WHEN MATCHED THEN UPDATE SET
    domain_name = source.domain_name,
    source_type = source.source_type,
    source_object = source.source_object,
    enabled = source.enabled,
    load_mode = source.load_mode,
    base_extract_sql = source.base_extract_sql,
    watermark_column = source.watermark_column,
    watermark_type = source.watermark_type,
    primary_keys = source.primary_keys,
    sequence_column = source.sequence_column,
    delete_indicator_column = source.delete_indicator_column,
    bronze_table = source.bronze_table,
    silver_current_table = source.silver_current_table,
    silver_history_table = source.silver_history_table,
    gold_table = source.gold_table,
    silver_transform_name = source.silver_transform_name,
    gold_publish_name = source.gold_publish_name,
    quality_rule_set = source.quality_rule_set,
    replay_mode_default = source.replay_mode_default,
    options_json = source.options_json,
    updated_ts = current_timestamp()
WHEN NOT MATCHED THEN INSERT *;